name: Deploy Flutter App directly to Firebase and Build Apk
description: 'Automate Flutter app deployment on Firebase, build APKs, & deploy to GitHub Releases. Streamline updates & save time!'
author: 'MXNXV-ERR'

branding:
  icon: arrow-up-right
  color: red

inputs:
  githubToken:
    description: 'For pushng artifacts to releases,Ensure read write access to workflow'
    required: false
    default: '${{secrets.GITHUB_TOKEN}}'
  firebaseServiceAcc:
    description: 'For publishing onto Firebase,for that specific app'
    required: true
    default: ""

runs:
  using: 'composite'
  steps: 
    # build_and_deploy:
    #   name: "Build & Release"
    #   runs-on: ubuntu-latest
    #   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: >-
        sudo snap install flutter --classic && flutter channel beta && flutter pub get && flutter build apk -debug --split-per-abi && flutter
        config --enable-web && flutter build web --web-renderer html --release
      shell: bash
    - name: Push to release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ inputs.githubToken}}
        tag: v1.0.${{github.run_number}}
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ inputs.githubToken }}'
        firebaseServiceAccount: '${{ inputs.firebaseServiceAcc }}'
        channelId: live
        projectId: '${{projectId}}'

