name: Deploy Flutter App directly to Firebase and Build Apk

'on':
  push:
    branches:
      - main
      - master
jobs:
  build_and_deploy:
    name: "Build & Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: >-
          sudo snap install flutter --classic && flutter channel beta && flutter pub get && flutter build apk -debug --split-per-abi && flutter
          config --enable-web && flutter build web --web-renderer html --release
      - name: Push to release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN}}
          tag: v1.0.${{github.run_number}}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODOAPP_432FE }}'
          channelId: live
          projectId: '${{projectId}}'


To automate the deployment of your Flutter app on Firebase and build APKs, create a GitHub Action workflow. The workflow will trigger on each push event, ensuring continuous integration. It will use Flutter's build tools to generate APKs and then deploy the app to Firebase Hosting using the Firebase CLI. Finally, the workflow will push the APKs to GitHub Releases, enabling easy distribution and version management. This streamlined process will save time and effort, making it convenient to deliver updates and improvements to your Flutter app.
